Resources:
  Appointments:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "appointmentId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "appointmentId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "Appointments"
